"""
Agent state definitions and Pydantic models for structured LLM output.
"""
from typing import TypedDict, Optional, List, Dict, Any, Literal
from pydantic import BaseModel, Field
from dataclasses import dataclass, field


# ──────────────────────────────────────────────
# Pydantic models for structured LLM output
# ──────────────────────────────────────────────

class TestScenario(BaseModel):
    """A test scenario generated by the Scenario Generator agent."""
    name: str = Field(description="Descriptive scenario name in Gherkin style")
    category: Literal[
        "happy_path", "business_rule", "validation",
        "error_handling", "boundary", "security"
    ] = Field(description="Test scenario category")
    description: str = Field(description="What is being tested and why")
    expected_outcome: str = Field(description="Expected result of the test")
    knowledge_sources: List[str] = Field(
        default_factory=list,
        description="Which spec/code/test chunks informed this scenario"
    )
    confidence: Literal["high", "medium", "low"] = Field(
        description="Confidence level based on how well-grounded the scenario is"
    )
    preconditions: List[str] = Field(
        default_factory=list,
        description="Setup steps required before the test"
    )
    test_data: Dict[str, Any] = Field(
        default_factory=dict,
        description="Key-value pairs for data-driven testing"
    )


class ScenarioList(BaseModel):
    """Wrapper for a list of generated scenarios (used for structured output)."""
    scenarios: List[TestScenario] = Field(description="List of generated test scenarios")


@dataclass
class CompanionDataFile:
    """A companion data file (CSV/Excel) generated alongside a .feature file."""
    filename: str       # e.g., "order-data.csv"
    content: str        # CSV content as string
    file_type: str      # "csv" or "excel"


class GeneratedFeature(BaseModel):
    """A generated Karate .feature file."""
    filename: str = Field(description="Feature file name, e.g. post-orders-gold-discount.feature")
    content: str = Field(description="Full .feature file content")
    scenario_name: str = Field(description="Name of the scenario this feature tests")
    knowledge_sources: List[str] = Field(
        default_factory=list,
        description="Knowledge sources that informed this feature"
    )
    reasoning: str = Field(
        default="",
        description="Why this test was generated this way"
    )
    companion_data_files: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Companion data files (CSV) to write alongside the feature"
    )


# ──────────────────────────────────────────────
# LangGraph Agent State
# ──────────────────────────────────────────────

class AgentState(TypedDict, total=False):
    """State that flows through the LangGraph workflow."""
    # Input
    endpoint_tag: str
    target_project: str

    # Stage 1: Context retrieval
    context_package: Optional[Any]  # ContextPackage from rag/retriever.py

    # Stage 2: Scenario generation
    scenarios: Optional[List[dict]]  # Serialized TestScenario dicts

    # Stage 3: Feature writing
    feature_files: Optional[List[dict]]  # Serialized GeneratedFeature dicts

    # Stage 4: Execution (stub for Week 3)
    execution_results: Optional[List[dict]]

    # Stage 5: Analysis (stub for Week 3)
    analysis: Optional[dict]

    # Control flow
    retry_count: int
    reasoning_chain: List[str]

    # Metadata
    dominant_data_pattern: str  # "inline_examples", "csv_read", "excel_read"
    error: Optional[str]
